# Publish to PyPI using Trusted Publishers (OIDC)
# - Builds distributions
# - Attaches them to the GitHub Release
# - Publishes via PyPI's trusted publisher workflow using pypa/gh-action-pypi-publish
#   https://docs.pypi.org/trusted-publishers/using-a-publisher/

name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build distributions and attach to release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history for tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine

      - name: Build distributions
        run: python -m build --sdist --wheel

      - name: Check distributions
        run: twine check dist/*

      - name: Upload distributions as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  pypi-publish:
    name: Publish package distributions to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
